type Caratteristiche = {
    descrizione: string;
    esposizione: string;
    speseCondominiali: number;
    speseExtra: string;
    ascensore: boolean;
    arredamento: string;
    balconi: string;
    terrazzi: string;
    box: string;
    giardino: string;
    taverna: string;
    mansarda: string;
    cantina: string;
    speseRiscaldamento: number;
    ariaCondizionata: string;
    proprieta: string;
    categoriaCatastale: string;
    rendita: number;
    impiantoElettrico: string;
    impiantoIdraulico: string;
    livelli: number;
    serramentiInterni: string;
    serramentiEsterni: string;
    portaBlindata: boolean;
    antifurto: string;
    citofono: string;
    annoCostruzione: number;
    combustibile: string;
    portineria: string;
    cablato: string;
    tipoLocazione: string;
    cauzione: string;
    reception: string;
    altezza: string;
    tipoContratto: string;
};

export default Caratteristiche;
